# These substitutions allow the end user to override certain values
substitutions:
  project_version: "1.0.5"
  device_name: "Switch"
  device_type: "switch"
  device_platform: "binary"
  device_icon: "mdi:toggle-switch-variant"
  restore_mode: "ALWAYS_OFF"

esphome:
  name: "onioff-switch-generic"
  friendly_name: "ONiOFF Generic Switch"
  project:
    name: curtistinkers.onioff-switch-generic
    version: ${project_version}

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://curtistinkers/esphome-onioff-smart-switch/onioff-switch-generic.yaml@main

packages:
  onioff-base: !include
    file: common/onioff-base.yaml
    vars:
      device_name: ${device_name}
      device_type: ${device_type}
      device_platform: ${device_platform}
      device_icon: ${device_icon}
      restore_mode: ${restore_mode}
