esphome:
  name: onioff-base
  # For (future) identification, configuration and updates
  project:
    name: curtistinkers.onioff-base
    version: 1.0.6

packages:
  project-esp8266: !include project-esp8266.yaml

status_led:
  pin:
    number: 1

binary_sensor:
  - platform: gpio
    id: toggle_button
    pin:
      number: 5
      inverted: true
      mode:
        input: true
        pullup: true
    internal: true
    on_press:
      then:
        - ${device_type}.toggle: relay_${device_type}
        - logger.log:
            format: ${device_name} button pressed
            level: DEBUG
            tag: ${device_type}
    on_click:
      min_length: 5s
      max_length: 10s
      then:
        - button.press: factory_reset_button

output:
  - platform: gpio
    id: relay
    pin: 12

${device_type}:
  - platform: ${device_platform}
    name: ${device_name}
    id: relay_${device_type}
    output: relay
    restore_mode: ${restore_mode}
    on_turn_on:
      then:
        - logger.log:
            format: ${device_name} turned on
            level: INFO
            tag: ${device_type}
    on_turn_off:
      then:
        - logger.log:
            format: ${device_name} turned off
            level: INFO
            tag: ${device_type}
